"""Symmetric encryption service for sensitive configuration fields (e.g. client_secret).

Reads AUTH_SECRET_KEY from environment. The key must be a 32-byte URL-safe base64 value
(as generated by `cryptography.fernet.Fernet.generate_key()`).
"""

import logging
import os

from cryptography.fernet import Fernet

logger = logging.getLogger(__name__)

_KEY = os.environ.get("AUTH_SECRET_KEY")

if not _KEY:
    # Development fallback — deterministic key so app can start without env config.
    # NEVER use this in production.
    _KEY = Fernet.generate_key().decode()
    logger.warning(
        "AUTH_SECRET_KEY not set — using auto-generated key. "
        "SSO client_secret will NOT survive restarts. Set AUTH_SECRET_KEY for production."
    )

_fernet = Fernet(_KEY if isinstance(_KEY, bytes) else _KEY.encode())


def encrypt(plaintext: str) -> str:
    """Encrypt a plaintext string and return the ciphertext as a UTF-8 string."""
    return _fernet.encrypt(plaintext.encode()).decode()


def decrypt(ciphertext: str) -> str:
    """Decrypt a ciphertext string and return the original plaintext."""
    return _fernet.decrypt(ciphertext.encode()).decode()
